= How to Post Blog Entries
:page-layout: post
:revdate: 2019-07-20 07:35:11 -0400
:page-permalink: /instructions/
:page-category: post
:page-tags: [instructions]

Even though this is a public site, I have posted this instruction to myself, because I sometimes go a long time between blog posts.
This post is a helpful reminder.

. Use the master branch for source content and configuration.
. Use `git branch` to check which branch git is on now.
. If not `master`, use `git checkout master` to switch to the master branch.
. Add a new `*.adoc` file to the _posts folder.
. Add the excerpt separator `//more` at the place where the excerpt stops.
. To build the site on local machine, use `jekyll build` in terminal.
. To preview on my local machine use `jekyll serve`.
. Preview the local jekyll site in a web browser at http://localhost:4000.
. Press ctrl-c to stop the process in the terminal.
. Use git for version control on the local machine using the gh-pages branch.
. Use gh-pages, for the generated static content produced by jekyll. 
. Use `git push githubRepo gh-pages` to push the new site to github.
. Jekyll is an active project and is updated frequently, so in terminal use `gem update github-pages`.

TIP: See https://github.com/asciidoctor/jekyll-asciidoc for changes as needed to the asciidoctor plugin for jekyll. 
Also see https://jekyllrb.com/docs/ for jekyll documentation.

== To Dos

- [ ] Get Travis CI turned on

I had been using Hugo, but since Github uses jekyll, I decided to go back to Jekyll.
One mistake was not adding a "How I did it" blog entry to remind myself after months without adding an entry.
Memory gets displaced by other things and other interests.